### ISSUE TITLE
[Feature Request] Add Dark Mode support

### ISSUE THREAD

**Issue by gingerchew** [DiegoRBaquero/PeerFast#4]
Since skeleton.css is so simple, I whipped this up real quick -

```css
/* Optional */
html {
	transition: filter 0.25s;
}
@media (prefers-color-scheme: dark) {
  html {
    background-color: #121314;
    filter: hue-rotate(180deg) invert(100%);
  }
}
```

<img width="678" alt="image" src="https://user-images.githubusercontent.com/26461046/108280865-ca467380-714c-11eb-9829-6540f492d0f8.png">

Which generated this on FireFox.

The black text on the blue of that button felt off, so I changed it to -

```css
@media (prefers-color-scheme: dark) {
  html {
    background-color: #121314;
    filter: hue-rotate(180deg) invert(100%);
  }
  .button.button-primary {
    color: #222;
  }
}
```

<img width="595" alt="image" src="https://user-images.githubusercontent.com/26461046/108281186-45a82500-714d-11eb-9c14-7d7d82fe5e8a.png">
